remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Center for Computational Psychiatry Speaker Series
description: >- # this means to ignore newlines until "baseurl:"
  Center for Computational Psychiatry Speaker Series
